basePath: /
host: localhost:8080
info:
  contact:
    email: danielkotelnikov20@gmail.com
    name: Daniel Kotelnikov
  description: Server API
  title: Records-App
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
